# Generated by Django 4.2.7 on 2023-11-25 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservapolideportivo',
            name='laboratorio',
        ),
        migrations.AddField(
            model_name='reservapolideportivo',
            name='polideportivo',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.CreateModel(
            name='ReservaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.laboratorio')),
            ],
        ),
    ]
