# Generated by Django 4.2.7 on 2023-12-04 17:17

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.horario')),
                ('laboratorio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaPolideportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.horario')),
                ('polideportivo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.polideportivo')),
            ],
        ),
    ]
