# Generated by Django 4.2.5 on 2023-12-09 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservalaboratorio',
            name='laboratorio_nombre',
        ),
        migrations.RemoveField(
            model_name='reservapolideportivo',
            name='polideportivo_nombre',
        ),
        migrations.AddField(
            model_name='reservalaboratorio',
            name='laboratorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.laboratorio'),
        ),
        migrations.AddField(
            model_name='reservapolideportivo',
            name='polideportivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.laboratorio'),
        ),
    ]
