# Generated by Django 4.2.7 on 2023-12-04 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_horario_remove_reservapolideportivo_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservalaboratorio',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.horario'),
        ),
        migrations.AlterField(
            model_name='reservapolideportivo',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.horario'),
        ),
    ]
