# Generated by Django 4.2.7 on 2023-11-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_reservapolideportivo_laboratorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservapolideportivo',
            name='polideportivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.polideportivo'),
        ),
    ]
