# Generated by Django 4.2.5 on 2023-12-09 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_reservalaboratorio_laboratorio_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservapolideportivo',
            name='polideportivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.polideportivo'),
        ),
    ]
