# Generated by Django 4.2.7 on 2023-11-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_reservapolideportivo_polideportivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservalaboratorio',
            name='laboratorio',
        ),
        migrations.RemoveField(
            model_name='reservapolideportivo',
            name='polideportivo',
        ),
        migrations.AddField(
            model_name='reservalaboratorio',
            name='laboratorio_nombre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservapolideportivo',
            name='polideportivo_nombre',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
