# Generated by Django 4.2.5 on 2023-12-09 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_reservapolideportivo_polideportivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservalaboratorio',
            name='laboratorio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='adminapp.laboratorio'),
        ),
        migrations.AlterField(
            model_name='reservapolideportivo',
            name='polideportivo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='adminapp.polideportivo'),
        ),
    ]
