# Generated by Django 4.2.7 on 2023-12-18 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_reservalaboratorio_laboratorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservalaboratorio',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.usuario'),
        ),
        migrations.AddField(
            model_name='reservapolideportivo',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.usuario'),
        ),
    ]
