# Generated by Django 4.2.7 on 2023-12-18 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_reservalaboratorio_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservalaboratorio',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.usuario'),
        ),
        migrations.AlterField(
            model_name='reservapolideportivo',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.usuario'),
        ),
    ]
